# Generated by Django 4.1.7 on 2023-06-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0004_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
