# Generated by Django 4.1.7 on 2023-06-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0005_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
